title: City of Austin Pages
baseurl: "/pages" # the subpath of your site, e.g. /blog
url: "https://cityofaustin.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: pretty

exclude:
  - bin
  - circle.yml
  - Gemfile
  - script
  - vendor
